### ISSUE TITLE
Stap 3 loopt vast

### ISSUE THREAD

**Issue by usds1** [bart147/GeoDynGemGWSW#27]

**Comment by usds1** [comment]
Results: {}
Results: {'OUTPUT': 'Joined_layer_4e773918_1bb6_495b_8a71_2620ffd981a1'}
Results: {'OUTPUT': 'Fixed_geometries_ffca2df6_b7b7_48ce_809d_58d4cab58611'}
36 feature(s) from input layer were successfully matched
Results: {'JOINED_COUNT': 36, 'OUTPUT': 'Joined_layer_c8cb5777_bac0_4c0c_8da9_9429c2b096a4', 'UNJOINABLE_COUNT': 0}
Results: {'OUTPUT': 'Calculated_cb8c3bc5_936c_446c_88a6_1a7cbd2bd328'}
Results: {'OUTPUT': 'Intersection_7df0a79a_abb0_43f6_9191_7801b69d81b1'}
No spatial index exists for join layer, performance will be severely degraded
Results: {'OUTPUT': 'Joined_layer_be366e13_0841_4e7b_90de_a7c4a30dd9eb'}
No spatial index exists for join layer, performance will be severely degraded
Results: {'OUTPUT': 'Joined_layer_5f5c16f0_b96d_4f0d_b381_ea9b3d190076'}
Results: {'OUTPUT': 'Extracted__attribute__a1e7d952_64e2_4374_981c_32f797ebf9f6'}
Results: {'OUTPUT': 'Extracted__attribute__b859687a_76f3_40be_b5ce_e53a704536e0'}
Results: {'OUTPUT': 'Added_geom_info_c307110b_7e10_4d73_a77f_50a930ffa565'}
Results: {'OUTPUT': 'Ordered_4fddf498_ab1e_4acb_9740_c4f4f28ad56e'}
Results: {'DUPLICATE_COUNT': 2, 'OUTPUT': 'Filtered__no_duplicates__f1d33507_49f4_4beb_816b_4a750baba66c', 'RETAINED_COUNT': 21}
Evaluation error in expression "sum(ExAFW_2124, BEM_ID)": Could not calculate aggregate for: "ExAFW_2124" (Field 'ExAFW_2124' not found)
Execution failed after 1.28 seconds

Loading resulting layers
Algorithm 'stap 3.) bereken afvalwaterprognose' finished


Stap 3 loopt vast en geeft dus geen resultaat. Lijkt dat de tool vast loopt op de plan cap kaart. Misschien op de kolomnamen? 2124 is niet 1 op 1 een kolomnaam uit het bronbestand.

**Comment by usds1** [comment]
Opmerking: de nieuwste plan kaart gaat vanaf 2022 (dus heeft een andere kolomnaam/attribuutnaam.

**Comment by bart147** [comment]
Dit heeft te maken met de juiste versie van Plancap. Gebruikers kunnen de juiste versie bij Mark Lamers krijgen die regelmatig afstemming heeft met Rigo.
Kan deze dan gesloten worden of moet er nog een (veld)aanpassing komen in de tool op dit moment?
